apiVersion: v1
data:
  index.html: |-
    <h1 id="simple-go-crud-app-with-postgresql-database">Hello gitops-app running!</h1>
kind: ConfigMap
metadata:
  name: landing-page
  labels:
     app: landing-page
