apiVersion: v1
data:
  index.html: |-
    <body bgcolor="#000000"><h1 style="color:white;">Hello gitops-app running!!!</h1></body>
kind: ConfigMap
metadata:
  name: landing-page
  labels:
     app: landing-page
