apiVersion: v1
data:
  index.html: |-
    <body bgcolor="#d3d3d3"><h1 style="color:blue;">Hello gitops-app running!!!</h1></body>
kind: ConfigMap
metadata:
  name: landing-page
  labels:
     app: landing-page
