apiVersion: v1
data:
  index.html: |-
    <body bgcolor="#000000">
    <h1 style="color:white;">Hello gitops-app running2!</h1>
    </body>
kind: ConfigMap
metadata:
  name: landing-page
  labels:
     app: landing-page
